language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
services:
  - docker
before_install:
  - docker pull silviof/docker-languagetool
  - docker run --rm -p 8010:8010 silviof/docker-languagetool
install:
  - travis_wait composer install
script:
  - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml
after_script:
  - php vendor/bin/coveralls -v
