language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
services:
  - docker
before_install:
  - make docker_build
  - make docker_run
install:
  - composer install
script:
  - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml
after_script:
  - php vendor/bin/coveralls -v
